baseURL: "https://taminemelissa.github.io" 
title: Mélissa Tamine
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 1

params:
    description: "Soon to be a PhD student @Inria & @CriteoAILab."
    author: Mélissa Tamine
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Mélissa Tamine
          subtitle: "Soon to be a PhD student @Inria & @CriteoAILab."
          imageUrl: "Photo_TAMINE_Mélissa.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Mélissa Tamine
          buttons:
            - name: Projects
              url: projects/
    socialIcons:
        - name: CV
          url: CV_TAMINE_Mélissa.pdf
        - name: Email
          url: mailto:melissa.tamine@ensae.fr
        #- name: Location
          #url: location/
        #- name: Office Hours
          #url: officehours/
        #- name: Google Scholar
          #url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        #- name: YouTube
          #url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/taminemelissa
        #- name: Substack
          #url: https://pmichaillat.substack.com
        - name: Twitter
          url: https://twitter.com/melissatamine
        - name: LinkedIn
          url: https://www.linkedin.com/in/m%C3%A9lissa-tamine/
        

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Mélissa Tamine"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
